### ISSUE TITLE
Change link to privacy policy on https://myopenhab.org/ 

### ISSUE THREAD

**Issue by MHerbst** [openhabfoundation/myopenhab.github.io#3]
The link to the privacy policy on page https://myopenhab.org/ points to http://www.openhabfoundation.org/privacy.html . Since some weeks myopenhab has its own pivacy policy page (http://www.myopenhab.org/privacy). Therefore it would be better to change the link to this page.

This would also allow us to remove the section about myopenhab from http://www.openhabfoundation.org/privacy.

**Comment by kaikreuzer** [comment]
@digitaldan: Could you update the link on https://myopenhab.org/login accordingly?

**Comment by kaikreuzer** [comment]
@digitaldan, another ping 5 months later - should be a pretty small change :-)

**Comment by MHerbst** [comment]
May I remind you of this little problem? @kaikreuzer @digitaldan :-)

**Comment by MHerbst** [comment]
I have to send another ping @kaikreuzer @digitaldan . This needs to be solved with regard to the GPDR actions.

**Comment by digitaldan** [comment]
I have updated the production config to point to "http://www.myopenhab.org/privacy" , it will take effect on the next restart of the app servers.  I have some PR's i need to merge and deploy this week which will require a restart.

**Comment by MHerbst** [comment]
Thanks :-)

**Comment by MHerbst** [comment]
With the latest openhab-cloud update (1.0.5) the link was changed :-).
